services:
  oracledb:
    image: gvenzl/oracle-free:23-slim-faststart
    container_name: oracledb
    environment:
      ORACLE_PASSWORD: "${ORACLE_PASSWORD:?set in .env}"
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oradata:/opt/oracle/oradata
    restart: unless-stopped

  nifi:
    image: apache/nifi:2.5.0
    container_name: nifi
    environment:
      NIFI_WEB_HTTPS_PORT: "8443"
      NIFI_WEB_HTTPS_HOST: "0.0.0.0"
      SINGLE_USER_CREDENTIALS_USERNAME: "${NIFI_USER:-admin}"
      SINGLE_USER_CREDENTIALS_PASSWORD: "${NIFI_PASS:?set in .env}"
    ports:
      - "8443:8443"
    volumes:
      - nifi_data:/opt/nifi/nifi-current
      - ./openflow/nifi-extensions:/opt/nifi/nifi-current/extensions:ro
      # Alle JDBC JARs liegen sauber im Host-Ordner ./openflow/nifi-lib/
      - ./openflow/nifi-lib/ojdbc11.jar:/opt/nifi/nifi-current/lib/ojdbc11.jar:ro
      - ./openflow/nifi-lib/snowflake-jdbc-3.26.0.jar:/opt/nifi/nifi-current/lib/snowflake-jdbc-3.26.0.jar:ro
    depends_on:
      - oracledb
    restart: unless-stopped

volumes:
  oradata:
  nifi_data:
